### ISSUE TITLE
git-crypt path ubuntu vs osx

### ISSUE THREAD

**Issue by basz** [shadowhand/git-encrypt#49]
Hello, I'm working with Vagrant/ansible setup to do development and I've notice a small incompatibility that might be simple to fix.

When ever I do a git checkout of my project within the Ubuntu box I run `git-crypt unlock` on the repository. Since the virtual box directory is exposed to the osx host machine I am able work on the repository as if it is a project installed on OSX (shared directories). Apparently the `git-crypt unlock` stores the complete (ubuntu) path to git-crypt in the repository. This then fails on osx as the path to git-crypt is different.

on osx i get these results;

```
$ git-crypt --version
git-crypt 0.5.0
$ which git-crypt
/usr/local/bin/git-crypt
$ git-crypt unlock git-crypt-key.key  
$ grep -R git-crypt ./.git/
./.git//config:[filter "git-crypt"]
./.git//config:	smudge = \"git-crypt\" smudge
./.git//config:	clean = \"git-crypt\" clean
./.git//config:[diff "git-crypt"]
./.git//config:	textconv = \"git-crypt\" diff
```

from ubuntu I get these results;

```
$ which git-crypt
/usr/bin/git-crypt
$ git-crypt --version
git-crypt 0.5.0
$ git-crypt unlock git-crypt-key.key  
$ grep -R git-crypt ./.git/
./.git/config:[filter "git-crypt"]
./.git/config:	smudge = \"/usr/bin/git-crypt\" smudge
./.git/config:	clean = \"/usr/bin/git-crypt\" clean
./.git/config:[diff "git-crypt"]
./.git/config:	textconv = \"/usr/bin/git-crypt\" diff
```

As you can see both git-crypt versions store a reference to the git-crypt executable differently which will be problematic in the described - admittedly not so mainstream - setup.

I'm aware that I can simply run `git-crypt unlock` from the host machine as a work around but I'm wondering if there is a better way to work around this.

So, is this something that can be fixed or configured?

**Comment by shadowhand** [comment]
I'm not sure how to solve this. If you find out, I'd be interested to see a PR!

**Comment by basz** [comment]
i think I might have misplaced this issue, thinking this was the original repository. So I've reposted it [here](https://github.com/AGWA/git-crypt/issues/71).

**Comment by shadowhand** [comment]
Well, they are both "original" but the other is much more secure.
